import mongoose from "mongoose";

const cartProductSchema = new mongoose.Schema({
    productTitle:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    rating:{
        type:Number,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    oldPrice:{
        type:Number,
    },
    discount:{
        type:Number,
    },
    size:{
        type:String,
    },
    weight:{
        type:String,
    },
    ram:{
        type:String,
    },
    color:{
        type:String,
        default:""
    },
    colorCode:{
        type:String,
        default:""
    },
    selectedOptions:{
        type:Object,
        default:{}
    },
    quantity:{
        type:Number,
        required:true
    },
    subTotal:{
        type:Number,
        required:true
    },
    productId:{
        type:String,
        required:true
    },
    countInStock:{
        type:Number,
        required:true
    },
    userId:{
        type:String,
        required:true
    },
    brand:{
        type:String,
    },
    source:{
        type:String,
        default:""
    },
    shopId:{
        type:String,
        default:""
    },
    shopLatitude:{
        type:Number,
    },
    shopLongitude:{
        type:Number,
    },
    restaurantId:{
        type:String,
        default:""
    },
    restaurantLatitude:{
        type:Number,
    },
    restaurantLongitude:{
        type:Number,
    }
},{
    timestamps : true
});

const CartProductModel = mongoose.model('cart',cartProductSchema)

export default CartProductModel